export const nodes = {
  peerPills: document.getElementById("peerPills"),
  liveBadge: document.getElementById("liveBadge"),
  warningBanner: document.getElementById("warningBanner"),
  connMode: document.getElementById("connMode"),
  connTransport: document.getElementById("connTransport"),
  connLastRest: document.getElementById("connLastRest"),
  connLastEvent: document.getElementById("connLastEvent"),
  connError: document.getElementById("connError"),
  settingsBtn: document.getElementById("settingsBtn"),
  settingsPanel: document.getElementById("settingsPanel"),
  beaconInput: document.getElementById("beaconInput"),
  metricsInput: document.getElementById("metricsInput"),
  nsSelect: document.getElementById("nsSelect"),
  modeSelect: document.getElementById("modeSelect"),
  applySettings: document.getElementById("applySettings"),
  topSlot: document.getElementById("topSlot"),
  topEpoch: document.getElementById("topEpoch"),
  topFinalized: document.getElementById("topFinalized"),
  topPart: document.getElementById("topPart"),
  validatorSubtitle: document.getElementById("validatorSubtitle"),
  leftSlot: document.getElementById("leftSlot"),
  proposerText: document.getElementById("proposerText"),
  phaseList: document.getElementById("phaseList"),
  slotCycleLabel: document.getElementById("slotCycleLabel"),
  countdown: document.getElementById("countdown"),
  finalizeHint: document.getElementById("finalizeHint"),
  statActive: document.getElementById("statActive"),
  statVoted: document.getElementById("statVoted"),
  statTotal: document.getElementById("statTotal"),
  statRate: document.getElementById("statRate"),
  justSlot: document.getElementById("justSlot"),
  justHash: document.getElementById("justHash"),
  finSlot: document.getElementById("finSlot"),
  finHash: document.getElementById("finHash"),
  gapTitle: document.getElementById("gapTitle"),
  gapFill: document.getElementById("gapFill"),
  chipWrap: document.getElementById("chipWrap"),
  mSlot: document.getElementById("mSlot"),
  mPart: document.getElementById("mPart"),
  mMissed: document.getElementById("mMissed"),
  mPeers: document.getElementById("mPeers"),
  dbgGoroutines: document.getElementById("dbgGoroutines"),
  dbgMemory: document.getElementById("dbgMemory"),
  dbgEvents: document.getElementById("dbgEvents"),
  dbgLastEvent: document.getElementById("dbgLastEvent")
};

export const chainCanvas = document.getElementById("chainCanvas");
export const chainCtx = chainCanvas.getContext("2d");
export const validatorCanvas = document.getElementById("validatorCanvas");
export const validatorCtx = validatorCanvas.getContext("2d");
